export type Role="Super Admin"|"Department Admin"|"Member"|"Intern";
export type Status="Inbox"|"Planned"|"Available"|"Assigned"|"In Progress"|"Blocked"|"In Review"|"Done"|"Cancelled"|"Backlog"|"In progress"|"In review";
export type User={id:string;name:string;email:string;role:Role;department:string;reportsTo?:string;active?:boolean};
export type Blocker={reason:string;need:string;waitingFor:string;severity:"Low"|"Medium"|"High"|"Critical";reportedBy:string;createdAt:string;resolvedAt?:string};
export type Comment={id:string;author:string;text:string;createdAt:string};
export type Task={id:string;title:string;project:string;department?:string;createdBy?:string;status:Status;assignee?:string;priority:"Critical"|"High"|"Medium"|"Low";createdDate?:string;startDate?:string;due:string;targetWeek?:string;description:string;criteria:string[];dependencies?:string[];comments?:Comment[];activity?:string[];reviewState?:"Not submitted"|"Awaiting review"|"Changes requested"|"Approved";attachments?:string[];pr?:string;blocker?:Blocker;weeklyCommitment?:boolean;available?:boolean;merged?:boolean};
export type Audit={id:string;actor:string;action:string;time:string};
export type Notice={id:string;userId:string;title:string;body:string;read:boolean;time:string};
export type Access={id:string;requester:string;department:string;resourceType:string;system:string;relatedTask:string;reason:string;status:"Pending"|"Approved"|"Rejected";date:string};
export const users:User[]=[
 {id:"u1",name:"Morgan Lee",email:"morgan@olyxee.com",role:"Super Admin",department:"Operations",active:true},
 {id:"u2",name:"Alisha Fatima",email:"alisha@olyxee.com",role:"Department Admin",department:"AI Engineering",reportsTo:"u1",active:true},
 {id:"u3",name:"Noah Williams",email:"noah@olyxee.com",role:"Intern",department:"AI Engineering",reportsTo:"u2",active:true},
 {id:"u4",name:"Sofia Chen",email:"sofia@olyxee.com",role:"Intern",department:"Product Engineering",reportsTo:"u6",active:true},
 {id:"u5",name:"Ethan Brooks",email:"ethan@olyxee.com",role:"Intern",department:"Data",reportsTo:"u7",active:true},
 {id:"u6",name:"Priya Nair",email:"priya@olyxee.com",role:"Department Admin",department:"Product Engineering",reportsTo:"u1",active:true},
 {id:"u7",name:"Tomás Reed",email:"tomas@olyxee.com",role:"Member",department:"Data",reportsTo:"u1",active:true}];
export const projects=["Orgni","Olyxee Logistics","Okiru","Internal Operations","Research"];
const base={department:"AI Engineering",createdBy:"u1",createdDate:"2026-09-14",targetWeek:"14–18 Sep 2026",criteria:["Acceptance criteria are agreed","Evidence is attached before review"],dependencies:[],comments:[],activity:["Task seeded for week 38"],attachments:[],reviewState:"Not submitted" as const};
export const seedTasks:Task[]=[
 {...base,id:"OLX-101",title:"Orgni Teams Integration",project:"Orgni",status:"In Review",assignee:"u2",priority:"High",due:"2026-09-16",description:"Connect Orgni team membership to the internal directory.",criteria:["Teams map to Orgni workspaces","Sync retries safely","Audit event is emitted"],pr:"https://github.com/olyxee/orgni/pull/184",reviewState:"Awaiting review",weeklyCommitment:true},
 {...base,id:"OLX-102",title:"Water Forecaster Simulation API",project:"Research",status:"Done",assignee:"u3",priority:"Critical",due:"2026-09-17",description:"Expose simulation runs for the forecasting prototype.",criteria:["API returns a run ID","Inputs are validated","README has a curl example"],pr:"https://github.com/olyxee/research/pull/142",merged:true,reviewState:"Approved",weeklyCommitment:true},
 {...base,department:"Product Engineering",id:"OLX-103",title:"Okiru Company Workspace",project:"Okiru",status:"Done",assignee:"u4",priority:"Medium",due:"2026-09-15",description:"Create the company workspace setup flow.",criteria:["Owner can create workspace","Duplicate names are handled","Audit event is emitted"],pr:"https://github.com/olyxee/okiru/pull/177",merged:true,reviewState:"Approved",weeklyCommitment:true},
 {...base,department:"Data",id:"OLX-104",title:"Olyxee Logistics Customs Automation",project:"Olyxee Logistics",status:"Blocked",assignee:"u5",priority:"High",due:"2026-09-18",description:"Automate customs document checks for shipments.",criteria:["Missing HS codes are flagged","A review queue is visible","Dry run is available"],blocker:{reason:"Staging customs credentials are unavailable.",need:"A read-only staging service account.",waitingFor:"Operations",severity:"High",reportedBy:"u5",createdAt:"2026-09-15"},weeklyCommitment:true},
 {...base,id:"OLX-105",title:"Orgni parser tests",project:"Orgni",status:"Done",assignee:"u2",priority:"Medium",due:"2026-09-14",description:"Increase parser coverage for team exports.",criteria:["Fixtures cover nested teams","Failure output is clear"],pr:"https://github.com/olyxee/orgni/pull/180",reviewState:"Approved",weeklyCommitment:true},
 {...base,department:"Operations",id:"OLX-106",title:"Friday Review CSV export",project:"Internal Operations",status:"Done",assignee:"u1",priority:"Medium",due:"2026-09-18",description:"Export the current Friday Review view.",criteria:["Exports filtered view","Filename contains week range"],reviewState:"Approved",weeklyCommitment:true},
 {...base,id:"OLX-107",title:"Forecast fixture set",project:"Research",status:"Planned",priority:"Medium",due:"2026-09-21",description:"Create versioned simulation fixtures.",criteria:["Fixtures are versioned","Update process is documented"],weeklyCommitment:true},
 {...base,id:"OLX-108",title:"Orgni sync progress indicator",project:"Orgni",status:"Done",assignee:"u2",priority:"Low",due:"2026-09-18",description:"Show progress while large team sets sync.",criteria:["Updates every two seconds","Handles reconnect"],reviewState:"Approved",weeklyCommitment:true},
 {...base,department:"Operations",id:"OLX-109",title:"Permissions matrix",project:"Internal Operations",status:"Done",assignee:"u1",priority:"Critical",due:"2026-09-14",description:"Define role permissions for Ops.",criteria:["Admin actions are explicit","Intern scope is documented"],reviewState:"Approved"},
 {...base,department:"Data",id:"OLX-110",title:"Shipment exception digest",project:"Olyxee Logistics",status:"Assigned",assignee:"u5",priority:"High",due:"2026-09-18",description:"Summarise shipment exceptions for daily review.",criteria:["Digest groups by severity","Owners are visible"]},
 {...base,department:"Product Engineering",id:"OLX-111",title:"Okiru billing settings",project:"Okiru",status:"Inbox",priority:"Low",due:"2026-09-23",description:"Add billing settings to the company workspace.",criteria:["Plan is displayed","Owner can update contact"]},
 {...base,id:"OLX-112",title:"Research run comparison",project:"Research",status:"In Review",assignee:"u3",priority:"High",due:"2026-09-17",description:"Compare the latest model runs.",criteria:["Baseline is recorded","Outliers have an owner"],pr:"https://github.com/olyxee/research/pull/42",reviewState:"Awaiting review"},
 {...base,department:"Data",id:"OLX-113",title:"Customs provider mapping",project:"Olyxee Logistics",status:"Blocked",assignee:"u5",priority:"High",due:"2026-09-19",description:"Map provider codes to internal shipment codes.",criteria:["All live providers mapped"],blocker:{reason:"Provider code list has changed.",need:"A confirmed mapping file.",waitingFor:"Logistics lead",severity:"Medium",reportedBy:"u5",createdAt:"2026-09-16"}},
 {...base,id:"OLX-114",title:"Orgni import validation",project:"Orgni",status:"Done",assignee:"u2",priority:"Medium",due:"2026-09-15",description:"Validate import size and shape.",criteria:["Invalid files are rejected"],pr:"https://github.com/olyxee/orgni/pull/186",reviewState:"Approved"},
 {...base,department:"Product Engineering",id:"OLX-115",title:"Okiru invite email",project:"Okiru",status:"In Progress",assignee:"u4",priority:"Medium",due:"2026-09-18",description:"Send invitations to workspace members.",criteria:["Invite is sent","Duplicate invites handled"]},
 {...base,department:"Operations",id:"OLX-116",title:"Release notes template",project:"Internal Operations",status:"Blocked",assignee:"u1",priority:"Low",due:"2026-09-18",description:"Standardise weekly release notes.",criteria:["Template has owners"],blocker:{reason:"No agreed owner for release notes.",need:"A named reviewer.",waitingFor:"Engineering leads",severity:"Low",reportedBy:"u1",createdAt:"2026-09-16"}},
 {...base,department:"Data",id:"OLX-117",title:"Customs dry-run report",project:"Olyxee Logistics",status:"Cancelled",priority:"Low",due:"2026-09-18",description:"Produce a dry-run summary.",criteria:["Summary includes exceptions"]},
 {...base,id:"OLX-118",title:"Simulation API README",project:"Research",status:"Planned",assignee:"u3",priority:"Low",due:"2026-09-18",description:"Document the simulation API.",criteria:["Setup is documented","Example request works"]}];
export const seedAccess:Access[]=[
 {id:"AR-31",requester:"u3",department:"AI Engineering",resourceType:"Repository",system:"GitHub private repository",relatedTask:"OLX-102",reason:"Need to open a PR for the simulation API.",status:"Pending",date:"16 Sep 2026"},
 {id:"AR-29",requester:"u5",department:"Data",resourceType:"Environment",system:"Staging customs service",relatedTask:"OLX-104",reason:"Required to validate customs automation.",status:"Pending",date:"15 Sep 2026"}];
export const seedAudit:Audit[]=[{id:"a1",actor:"Morgan Lee",action:"Created week 38 commitments",time:"14 Sep, 09:00"},{id:"a2",actor:"Alisha Fatima",action:"Submitted OLX-101 for review",time:"15 Sep, 16:22"},{id:"a3",actor:"Noah Williams",action:"Started OLX-102",time:"16 Sep, 09:14"},{id:"a4",actor:"System",action:"GitHub evidence synced for OLX-105",time:"16 Sep, 08:51"}];
export const seedNotices:Notice[]=[{id:"n1",userId:"u3",title:"Access request needs review",body:"Your GitHub repository request is pending.",read:false,time:"1 hour ago"},{id:"n2",userId:"u2",title:"Work submitted",body:"OLX-101 is ready for review.",read:false,time:"2 hours ago"},{id:"n3",userId:"u5",title:"Task blocked",body:"OLX-104 needs customs credentials.",read:false,time:"Yesterday"}];
export const departments=[["AI Engineering","Alisha Fatima","5 members"],["Product Engineering","Priya Nair","6 members"],["Data","Tomás Reed","4 members"],["Operations","Morgan Lee","3 members"]];